# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-04 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BandwidthDelay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bandWidth', models.CharField(default='0', max_length=20)),
                ('delay', models.CharField(default='0', max_length=20)),
                ('jetter', models.CharField(default='0', max_length=20)),
                ('bdTIme', models.CharField(default='00:00:00', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='HTTPCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('httpCode', models.CharField(default='0', max_length=10)),
                ('responseTIme', models.CharField(default='00:00:00', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ReTran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reTran', models.CharField(default='0', max_length=10)),
                ('reTranTIme', models.CharField(default='00:00:00', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srcTodst', models.CharField(default='0', max_length=100)),
                ('urlAdd', models.CharField(default='0', max_length=50)),
                ('reqTIme', models.CharField(default='00:00:00', max_length=40)),
                ('TCPtime', models.CharField(default='0', max_length=10)),
            ],
        ),
    ]
