# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-14 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packetInfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandwidthdelay',
            name='ipPlay',
            field=models.CharField(default='0.0.0.0', max_length=40),
        ),
        migrations.AddField(
            model_name='retran',
            name='ipPlay',
            field=models.CharField(default='0.0.0.0', max_length=40),
        ),
        migrations.AddField(
            model_name='source',
            name='ipPlay',
            field=models.CharField(default='0.0.0.0', max_length=40),
        ),
    ]
