# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-15 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packetInfo', '0002_auto_20170414_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='httpcode',
            name='ipPlay',
            field=models.CharField(default='0.0.0.0', max_length=40),
        ),
    ]
