# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-21 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packetInfo', '0003_httpcode_ipplay'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default='0.0.0.0', max_length=40)),
                ('filename', models.CharField(default='0', max_length=60)),
                ('time', models.CharField(default='00:00:00', max_length=40)),
                ('width', models.IntegerField(default=0, max_length=10)),
                ('height', models.IntegerField(default=0, max_length=10)),
                ('framerate', models.IntegerField(default=0, max_length=10)),
                ('ext', models.CharField(default='0', max_length=20)),
                ('codecname', models.CharField(default='0', max_length=20)),
                ('pixfmt', models.CharField(default='0', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VideoQuality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default='0.0.0.0', max_length=40)),
                ('filename', models.CharField(default='0', max_length=60)),
                ('time', models.CharField(default='00:00:00', max_length=40)),
                ('psnr', models.FloatField(default=0.0, max_length=15)),
            ],
        ),
    ]
